version: "3.9"
services:
  python:
    container_name: python
    build: .
    volumes:
      - tg-bot:/bot
    environment:
      BOT_TOKEN:
      DB_HOST: "host.docker.internal"
      DB_PORT: 5432
      DB_PASSWORD: "password"
      DB_USER: "postgres"
      DB_NAME: "telegram"
    networks:
      - tg_bot_network
      

  ollama:
    volumes:
      - llm-service:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:0.1.27
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - tg_bot_network

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    volumes:
      - llm-service:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3000:8080
    environment:
      - '/ollama/api=http://ollama:11434/api'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:16.2
    environment:
      POSTGRES_DB: "telegram"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - tg-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d telegram" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - tg_bot_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.3
    environment:
      PGADMIN_DEFAULT_EMAIL: "email@domain.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - tg-db:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - tg_bot_network

volumes:
  tg-db:
  tg-bot:
  llm-service:

networks:
  tg_bot_network:
    driver: bridge