"""empty message

Revision ID: 894a7e894c42
Revises: 
Create Date: 2024-03-17 19:29:54.749407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '894a7e894c42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operating', sa.Boolean(), nullable=True),
    sa.Column('last_activity_time', sa.DateTime(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('context', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('container_id', sa.SMALLINT(), nullable=True),
    sa.Column('permission', sa.SMALLINT(), nullable=True),
    sa.Column('processing', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('state', sa.SMALLINT(), nullable=True),
    sa.Column('expire_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('users')
    op.drop_table('containers')
    # ### end Alembic commands ###
